apiVersion: v1
kind: Service
metadata:
  name: oracle-ca-service
  labels: {
    component: oracle,
    type: ca
  }
spec:
  type: ClusterIP
  selector:
    component: oracle
    type: ca
  ports:
    - port: 7054
      targetPort: 7054
