apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: myapp3-deployment
spec: # Dictionary
  replicas: 1
  selector:
    matchLabels:
      app: myapp3
  template:  
    metadata: # Dictionary
      name: myapp3-pod
      labels: # Dictionary
        app: myapp3  # Key value paids
    spec:
      containers: # List
        - name: myapp3-container
          image: paulbouwer/hello-kubernetes:1.8
          ports: 
            - containerPort: 8080
---
apiVersion: v1
kind: Service 
metadata:
  name: deployment-loadbalancer-service
spec:
  #type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: myapp3
  ports: 
    - name: http
      port: 8080 # Service Port
      targetPort: 8080 # Container Port