apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mount/fca53bc43807c44379d142c/hlf-file-share"
    server: fca53bc43807c44379d142c.file.core.windows.net # :/fca53bc43807c44379d142c/1hlf-file-share
  # azureFile:
  #   secretName: azure-secret
  #   shareName: hlf-file-share # fca53bc43807c44379d142c # nfs3share
  #   readOnly: false
  # mountOptions:
  #   - nolock
  #   - vers=4
  #   - minorversion=1
  #   - sec=sys
  #   - proto=tcp
