apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" # my-azurefile-sc
  resources:
    requests:
      storage: 10Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: efs-burst-persistent-volume-claim
# spec:
#   storageClassName: my-azurefile-sc
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi
