apiVersion: v1
kind: Service 
metadata:
  name: auth-svc
  namespace: ms-dev
spec:
  selector:
    app: auth-deployment
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP