apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: nodejs-app-deployment
  labels:
    app: nodejs-app
spec: # Dictionary
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:  
    metadata: # Dictionary
      name: nodejs-app-pod
      labels: # Dictionary
        app: nodejs-app  # Key value paids
    spec:
      containers: # List
        - name: nodejs-app
          image: papanadappt/my-node-app:0.1.1-secret
          imagePullPolicy: Always
          ports: 
            - containerPort: 8081
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "webappdb"            
            - name: DB_USERNAME
              value: "root"            
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password