kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: managed-premium-retain-sc
  resources:
    requests:
      storage: 2Gi
