apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: managed-premium-retain-sc
provisioner: disk.csi.azure.com # kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer 
allowVolumeExpansion: true 
parameters:
  storageaccounttype: Standard_LRS # Premium_LRS # Standard_LRS
  kind: managed