apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: nodejs-app-deployment
  labels:
    app: nodejs-app
spec: # Dictionary
  replicas: 10
  selector:
    matchLabels:
      app: nodejs-app
  template:  
    metadata: # Dictionary
      name: nodejs-app-pod
      labels: # Dictionary
        app: nodejs-app  # Key value paids
    spec:
      containers: # List
        - name: nodejs-app
          image: papanadappt/my-node-app:latest
          ports: 
            - containerPort: 8081
---
apiVersion: v1
kind: Service 
metadata:
  name: nodejs-app-clusterip-service
  labels:
    app: nodejs-app
spec:
  # type: ClusterIp # LoadBalancer # ClusterIp, # NodePort
  selector:
    app: nodejs-app
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 8081 # Container Port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejsapp-ingress-service
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodejs-app-clusterip-service
                port:
                  number: 80