apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-burst-persistent-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: hlf-file-share # fca53bc43807c44379d142c # nfs3share
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - mfsymlinks
    - nobrl
