apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-burst-persistent-volume
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "f4b8a5c4ed6ad495aa41372/hlf-file-share"
    server: f4b8a5c4ed6ad495aa41372.file.core.windows.net
  # azureFile:
  #   secretName: azure-secret
  #   shareName: hlf-file-share # fca53bc43807c44379d142c # nfs3share
  #   readOnly: false
  mountOptions:
    - nolock
    - vers=3
    - sec=sys
    - proto=tcp
