
spec:
  storageClassName: my-azurefile-sc
  
  volumeMode: Filesystem

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-burst-persistent-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: nfs3share
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - mfsymlinks
    - nobrl
