apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-claim
spec:
  storageClassName: my-azurefile-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi  


