apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-claim
spec:
  storageClassName: my-azurefile-sc # azuredisk-csi-premium-zrs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi  
  #volumeMode: Block


