apiVersion: v1
kind: PersistentVolume
metadata:
  name: state
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: state
  resources:
    requests:
      storage: 100Gi